export const START_LOADER = "START_LOADER";
export const STOP_LOADER = "STOP_LOADER";
export const LIST_DATA = "LIST DATA";
export const LIST_DATA_SUCCESS = "LIST_DATA_SUCCESS";
export const LIST_DATA_FAILED = "LIST_DATA_FAILED";
